#!/usr/bin/env bash

gsettings reset org.nemo.compact-view all-columns-have-same-width
gsettings reset org.nemo.compact-view default-zoom-level
gsettings reset org.nemo.desktop background-fade
gsettings reset org.nemo.desktop computer-icon-visible
gsettings reset org.nemo.desktop desktop-layout
gsettings reset org.nemo.desktop font
gsettings reset org.nemo.desktop home-icon-visible
gsettings reset org.nemo.desktop horizontal-grid-adjust
gsettings reset org.nemo.desktop ignored-desktop-handlers
gsettings reset org.nemo.desktop network-icon-visible
gsettings reset org.nemo.desktop show-desktop-icons
gsettings reset org.nemo.desktop show-orphaned-desktop-icons
gsettings reset org.nemo.desktop text-ellipsis-limit
gsettings reset org.nemo.desktop trash-icon-visible
gsettings reset org.nemo.desktop use-desktop-grid
gsettings reset org.nemo.desktop vertical-grid-adjust
gsettings reset org.nemo.desktop volumes-visible
gsettings reset org.nemo.icon-view captions
gsettings reset org.nemo.icon-view default-use-tighter-layout
gsettings reset org.nemo.icon-view default-zoom-level
gsettings reset org.nemo.icon-view labels-beside-icons
gsettings reset org.nemo.icon-view text-ellipsis-limit
gsettings reset org.nemo.icon-view thumbnail-size
gsettings reset org.nemo.list-view default-column-order
gsettings reset org.nemo.list-view default-visible-columns
gsettings reset org.nemo.list-view default-zoom-level
gsettings reset org.nemo.plugins disabled-actions
gsettings reset org.nemo.plugins disabled-extensions
gsettings reset org.nemo.plugins disabled-scripts
gsettings reset org.nemo.preferences always-use-browser
gsettings reset org.nemo.preferences bulk-rename-tool
gsettings reset org.nemo.preferences click-double-parent-folder
gsettings reset org.nemo.preferences click-policy
gsettings reset org.nemo.preferences close-device-view-on-device-eject
gsettings reset org.nemo.preferences confirm-move-to-trash
gsettings reset org.nemo.preferences confirm-trash
gsettings reset org.nemo.preferences context-menus-show-all-actions
gsettings reset org.nemo.preferences date-font-choice
gsettings reset org.nemo.preferences date-format
gsettings reset org.nemo.preferences default-folder-viewer
gsettings reset org.nemo.preferences default-sort-in-reverse-order
gsettings reset org.nemo.preferences default-sort-order
gsettings reset org.nemo.preferences deferred-attribute-preload-limit
gsettings reset org.nemo.preferences desktop-is-home-dir
gsettings reset org.nemo.preferences detect-content
gsettings reset org.nemo.preferences disable-menu-warning
gsettings reset org.nemo.preferences enable-delete
gsettings reset org.nemo.preferences enable-mime-actions-make-executable
gsettings reset org.nemo.preferences executable-text-activation
gsettings reset org.nemo.preferences ignore-view-metadata
gsettings reset org.nemo.preferences image-viewers-with-external-sort
gsettings reset org.nemo.preferences inherit-folder-viewer
gsettings reset org.nemo.preferences inherit-show-thumbnails
gsettings reset org.nemo.preferences last-server-connect-method
gsettings reset org.nemo.preferences mouse-back-button
gsettings reset org.nemo.preferences mouse-forward-button
gsettings reset org.nemo.preferences mouse-use-extra-buttons
gsettings reset org.nemo.preferences never-queue-file-ops
gsettings reset org.nemo.preferences quick-renames-with-pause-in-between
gsettings reset org.nemo.preferences show-advanced-permissions
gsettings reset org.nemo.preferences show-bookmarks-in-to-menus
gsettings reset org.nemo.preferences show-compact-view-icon-toolbar
gsettings reset org.nemo.preferences show-computer-icon-toolbar
gsettings reset org.nemo.preferences show-directory-item-counts
gsettings reset org.nemo.preferences show-edit-icon-toolbar
gsettings reset org.nemo.preferences show-full-path-titles
gsettings reset org.nemo.preferences show-hidden-files
gsettings reset org.nemo.preferences show-home-icon-toolbar
gsettings reset org.nemo.preferences show-icon-view-icon-toolbar
gsettings reset org.nemo.preferences show-image-thumbnails
gsettings reset org.nemo.preferences show-list-view-icon-toolbar
gsettings reset org.nemo.preferences show-location-entry
gsettings reset org.nemo.preferences show-new-folder-icon-toolbar
gsettings reset org.nemo.preferences show-next-icon-toolbar
gsettings reset org.nemo.preferences show-open-in-terminal-toolbar
gsettings reset org.nemo.preferences show-places-in-to-menus
gsettings reset org.nemo.preferences show-previous-icon-toolbar
gsettings reset org.nemo.preferences show-reload-icon-toolbar
gsettings reset org.nemo.preferences show-root-warning
gsettings reset org.nemo.preferences show-search-icon-toolbar
gsettings reset org.nemo.preferences show-show-thumbnails-toolbar
gsettings reset org.nemo.preferences show-up-icon-toolbar
gsettings reset org.nemo.preferences size-prefixes
gsettings reset org.nemo.preferences sort-directories-first
gsettings reset org.nemo.preferences sort-favorites-first
gsettings reset org.nemo.preferences start-with-dual-pane
gsettings reset org.nemo.preferences swap-trash-delete
gsettings reset org.nemo.preferences tabs-open-position
gsettings reset org.nemo.preferences thumbnail-limit
gsettings reset org.nemo.preferences thumbnail-threads
gsettings reset org.nemo.preferences tooltips-in-icon-view
gsettings reset org.nemo.preferences tooltips-in-list-view
gsettings reset org.nemo.preferences tooltips-on-desktop
gsettings reset org.nemo.preferences tooltips-show-access-date
gsettings reset org.nemo.preferences tooltips-show-birth-date
gsettings reset org.nemo.preferences tooltips-show-file-type
gsettings reset org.nemo.preferences tooltips-show-mod-date
gsettings reset org.nemo.preferences tooltips-show-path
gsettings reset org.nemo.preferences treat-root-as-normal
gsettings reset org.nemo.preferences.menu-config background-menu-create-new-folder
gsettings reset org.nemo.preferences.menu-config background-menu-open-as-root
gsettings reset org.nemo.preferences.menu-config background-menu-open-in-terminal
gsettings reset org.nemo.preferences.menu-config background-menu-paste
gsettings reset org.nemo.preferences.menu-config background-menu-properties
gsettings reset org.nemo.preferences.menu-config background-menu-scripts
gsettings reset org.nemo.preferences.menu-config background-menu-show-hidden-files
gsettings reset org.nemo.preferences.menu-config desktop-menu-customize
gsettings reset org.nemo.preferences.menu-config iconview-menu-arrange-items
gsettings reset org.nemo.preferences.menu-config iconview-menu-organize-by-name
gsettings reset org.nemo.preferences.menu-config selection-menu-copy
gsettings reset org.nemo.preferences.menu-config selection-menu-copy-to
gsettings reset org.nemo.preferences.menu-config selection-menu-cut
gsettings reset org.nemo.preferences.menu-config selection-menu-duplicate
gsettings reset org.nemo.preferences.menu-config selection-menu-favorite
gsettings reset org.nemo.preferences.menu-config selection-menu-make-link
gsettings reset org.nemo.preferences.menu-config selection-menu-move-to
gsettings reset org.nemo.preferences.menu-config selection-menu-move-to-trash
gsettings reset org.nemo.preferences.menu-config selection-menu-open
gsettings reset org.nemo.preferences.menu-config selection-menu-open-as-root
gsettings reset org.nemo.preferences.menu-config selection-menu-open-in-new-tab
gsettings reset org.nemo.preferences.menu-config selection-menu-open-in-new-window
gsettings reset org.nemo.preferences.menu-config selection-menu-open-in-terminal
gsettings reset org.nemo.preferences.menu-config selection-menu-paste
gsettings reset org.nemo.preferences.menu-config selection-menu-pin
gsettings reset org.nemo.preferences.menu-config selection-menu-properties
gsettings reset org.nemo.preferences.menu-config selection-menu-rename
gsettings reset org.nemo.preferences.menu-config selection-menu-scripts
gsettings reset org.nemo.search search-content-case-sensitive
gsettings reset org.nemo.search search-content-history
gsettings reset org.nemo.search search-content-history-length
gsettings reset org.nemo.search search-content-use-raw
gsettings reset org.nemo.search search-content-use-regex
gsettings reset org.nemo.search search-file-case-sensitive
gsettings reset org.nemo.search search-file-history
gsettings reset org.nemo.search search-files-recursively
gsettings reset org.nemo.search search-regex-format
gsettings reset org.nemo.search search-reverse-sort
gsettings reset org.nemo.search search-skip-folders
gsettings reset org.nemo.search search-sort-column
gsettings reset org.nemo.search search-visible-columns
gsettings reset org.nemo.sidebar-panels.tree show-only-directories
gsettings reset org.nemo.window-state bookmarks-expanded
gsettings reset org.nemo.window-state devices-expanded
gsettings reset org.nemo.window-state geometry
gsettings reset org.nemo.window-state maximized
gsettings reset org.nemo.window-state my-computer-expanded
gsettings reset org.nemo.window-state network-expanded
gsettings reset org.nemo.window-state side-pane-view
gsettings reset org.nemo.window-state sidebar-bookmark-breakpoint
gsettings reset org.nemo.window-state sidebar-width
gsettings reset org.nemo.window-state start-with-location-bar
gsettings reset org.nemo.window-state start-with-menu-bar
gsettings reset org.nemo.window-state start-with-sidebar
gsettings reset org.nemo.window-state start-with-status-bar
gsettings reset org.nemo.window-state start-with-toolbar
