#!/usr/bin/env bash

gsettings set org.nemo.compact-view all-columns-have-same-width false
gsettings set org.nemo.compact-view default-zoom-level 'standard'
gsettings set org.nemo.desktop background-fade true
gsettings set org.nemo.desktop computer-icon-visible false
gsettings set org.nemo.desktop desktop-layout 'true::false'
gsettings set org.nemo.desktop font 'Sans 12'
gsettings set org.nemo.desktop home-icon-visible false
gsettings set org.nemo.desktop horizontal-grid-adjust 1.0
gsettings set org.nemo.desktop ignored-desktop-handlers "['conky', 'Showtime', 'desktop_weather']"
gsettings set org.nemo.desktop network-icon-visible false
gsettings set org.nemo.desktop show-desktop-icons true
gsettings set org.nemo.desktop show-orphaned-desktop-icons true
gsettings set org.nemo.desktop text-ellipsis-limit 2
gsettings set org.nemo.desktop trash-icon-visible false
gsettings set org.nemo.desktop use-desktop-grid false
gsettings set org.nemo.desktop vertical-grid-adjust 1.0
gsettings set org.nemo.desktop volumes-visible false
gsettings set org.nemo.icon-view captions "['none', 'size', 'date_modified']"
gsettings set org.nemo.icon-view default-use-tighter-layout false
gsettings set org.nemo.icon-view default-zoom-level 'small'
gsettings set org.nemo.icon-view labels-beside-icons false
gsettings set org.nemo.icon-view text-ellipsis-limit "['3']"
gsettings set org.nemo.icon-view thumbnail-size 64
gsettings set org.nemo.list-view default-column-order "['name', 'size', 'type', 'date_modified']"
gsettings set org.nemo.list-view default-visible-columns "['name', 'size', 'type', 'date_modified']"
gsettings set org.nemo.list-view default-zoom-level 'standard'
gsettings set org.nemo.plugins disabled-actions "[]"
gsettings set org.nemo.plugins disabled-extensions "[]"
gsettings set org.nemo.plugins disabled-scripts "[]"
gsettings set org.nemo.preferences always-use-browser true
gsettings set org.nemo.preferences bulk-rename-tool @ay "[]"
gsettings set org.nemo.preferences click-double-parent-folder false
gsettings set org.nemo.preferences click-policy 'double'
gsettings set org.nemo.preferences close-device-view-on-device-eject false
gsettings set org.nemo.preferences confirm-move-to-trash true
gsettings set org.nemo.preferences confirm-trash true
gsettings set org.nemo.preferences context-menus-show-all-actions false
gsettings set org.nemo.preferences date-font-choice 'auto-mono'
gsettings set org.nemo.preferences date-format 'iso'
gsettings set org.nemo.preferences default-folder-viewer 'list-view'
gsettings set org.nemo.preferences default-sort-in-reverse-order false
gsettings set org.nemo.preferences default-sort-order 'name'
gsettings set org.nemo.preferences deferred-attribute-preload-limit 150
gsettings set org.nemo.preferences desktop-is-home-dir false
gsettings set org.nemo.preferences detect-content true
gsettings set org.nemo.preferences disable-menu-warning false
gsettings set org.nemo.preferences enable-delete true
gsettings set org.nemo.preferences enable-mime-actions-make-executable false
gsettings set org.nemo.preferences executable-text-activation 'ask'
gsettings set org.nemo.preferences ignore-view-metadata true
gsettings set org.nemo.preferences image-viewers-with-external-sort "['xviewer', 'feh', 'sxiv']"
gsettings set org.nemo.preferences inherit-folder-viewer false
gsettings set org.nemo.preferences inherit-show-thumbnails false
gsettings set org.nemo.preferences last-server-connect-method 2
gsettings set org.nemo.preferences mouse-back-button 8
gsettings set org.nemo.preferences mouse-forward-button 9
gsettings set org.nemo.preferences mouse-use-extra-buttons true
gsettings set org.nemo.preferences never-queue-file-ops false
gsettings set org.nemo.preferences quick-renames-with-pause-in-between true
gsettings set org.nemo.preferences show-advanced-permissions false
gsettings set org.nemo.preferences show-bookmarks-in-to-menus true
gsettings set org.nemo.preferences show-compact-view-icon-toolbar true
gsettings set org.nemo.preferences show-computer-icon-toolbar false
gsettings set org.nemo.preferences show-directory-item-counts 'local-only'
gsettings set org.nemo.preferences show-edit-icon-toolbar true
gsettings set org.nemo.preferences show-full-path-titles true
gsettings set org.nemo.preferences show-hidden-files false
gsettings set org.nemo.preferences show-home-icon-toolbar false
gsettings set org.nemo.preferences show-icon-view-icon-toolbar true
gsettings set org.nemo.preferences show-image-thumbnails 'local-only'
gsettings set org.nemo.preferences show-list-view-icon-toolbar true
gsettings set org.nemo.preferences show-location-entry false
gsettings set org.nemo.preferences show-new-folder-icon-toolbar true
gsettings set org.nemo.preferences show-next-icon-toolbar true
gsettings set org.nemo.preferences show-open-in-terminal-toolbar true
gsettings set org.nemo.preferences show-places-in-to-menus true
gsettings set org.nemo.preferences show-previous-icon-toolbar true
gsettings set org.nemo.preferences show-reload-icon-toolbar true
gsettings set org.nemo.preferences show-root-warning true
gsettings set org.nemo.preferences show-search-icon-toolbar true
gsettings set org.nemo.preferences show-show-thumbnails-toolbar true
gsettings set org.nemo.preferences show-up-icon-toolbar true
gsettings set org.nemo.preferences size-prefixes 'base-10'
gsettings set org.nemo.preferences sort-directories-first true
gsettings set org.nemo.preferences sort-favorites-first true
gsettings set org.nemo.preferences start-with-dual-pane false
gsettings set org.nemo.preferences swap-trash-delete false
gsettings set org.nemo.preferences tabs-open-position 'after-current-tab'
gsettings set org.nemo.preferences thumbnail-limit 5242880
gsettings set org.nemo.preferences thumbnail-threads -1
gsettings set org.nemo.preferences tooltips-in-icon-view true
gsettings set org.nemo.preferences tooltips-in-list-view true
gsettings set org.nemo.preferences tooltips-on-desktop true
gsettings set org.nemo.preferences tooltips-show-access-date false
gsettings set org.nemo.preferences tooltips-show-birth-date false
gsettings set org.nemo.preferences tooltips-show-file-type false
gsettings set org.nemo.preferences tooltips-show-mod-date false
gsettings set org.nemo.preferences tooltips-show-path false
gsettings set org.nemo.preferences treat-root-as-normal false
gsettings set org.nemo.preferences.menu-config background-menu-create-new-folder true
gsettings set org.nemo.preferences.menu-config background-menu-open-as-root true
gsettings set org.nemo.preferences.menu-config background-menu-open-in-terminal true
gsettings set org.nemo.preferences.menu-config background-menu-paste true
gsettings set org.nemo.preferences.menu-config background-menu-properties true
gsettings set org.nemo.preferences.menu-config background-menu-scripts true
gsettings set org.nemo.preferences.menu-config background-menu-show-hidden-files true
gsettings set org.nemo.preferences.menu-config desktop-menu-customize true
gsettings set org.nemo.preferences.menu-config iconview-menu-arrange-items true
gsettings set org.nemo.preferences.menu-config iconview-menu-organize-by-name true
gsettings set org.nemo.preferences.menu-config selection-menu-copy true
gsettings set org.nemo.preferences.menu-config selection-menu-copy-to true
gsettings set org.nemo.preferences.menu-config selection-menu-cut true
gsettings set org.nemo.preferences.menu-config selection-menu-duplicate true
gsettings set org.nemo.preferences.menu-config selection-menu-favorite true
gsettings set org.nemo.preferences.menu-config selection-menu-make-link true
gsettings set org.nemo.preferences.menu-config selection-menu-move-to true
gsettings set org.nemo.preferences.menu-config selection-menu-move-to-trash true
gsettings set org.nemo.preferences.menu-config selection-menu-open true
gsettings set org.nemo.preferences.menu-config selection-menu-open-as-root true
gsettings set org.nemo.preferences.menu-config selection-menu-open-in-new-tab true
gsettings set org.nemo.preferences.menu-config selection-menu-open-in-new-window true
gsettings set org.nemo.preferences.menu-config selection-menu-open-in-terminal true
gsettings set org.nemo.preferences.menu-config selection-menu-paste true
gsettings set org.nemo.preferences.menu-config selection-menu-pin true
gsettings set org.nemo.preferences.menu-config selection-menu-properties true
gsettings set org.nemo.preferences.menu-config selection-menu-rename true
gsettings set org.nemo.preferences.menu-config selection-menu-scripts true
gsettings set org.nemo.search search-content-case-sensitive false
gsettings set org.nemo.search search-content-history "[]"
gsettings set org.nemo.search search-content-history-length 10
gsettings set org.nemo.search search-content-use-raw false
gsettings set org.nemo.search search-content-use-regex false
gsettings set org.nemo.search search-file-case-sensitive false
gsettings set org.nemo.search search-file-history "[]"
gsettings set org.nemo.search search-files-recursively true
gsettings set org.nemo.search search-regex-format 'pcre'
gsettings set org.nemo.search search-reverse-sort false
gsettings set org.nemo.search search-skip-folders "['/dev', '/proc', '/sys', 'dosdevices', '.git']"
gsettings set org.nemo.search search-sort-column ''
gsettings set org.nemo.search search-visible-columns "[]"
gsettings set org.nemo.sidebar-panels.tree show-only-directories true
gsettings set org.nemo.window-state bookmarks-expanded true
gsettings set org.nemo.window-state devices-expanded true
gsettings set org.nemo.window-state geometry '800x550+286+95'
gsettings set org.nemo.window-state maximized false
gsettings set org.nemo.window-state my-computer-expanded true
gsettings set org.nemo.window-state network-expanded true
gsettings set org.nemo.window-state side-pane-view 'places'
gsettings set org.nemo.window-state sidebar-bookmark-breakpoint 5
gsettings set org.nemo.window-state sidebar-width 180
gsettings set org.nemo.window-state start-with-location-bar true
gsettings set org.nemo.window-state start-with-menu-bar false
gsettings set org.nemo.window-state start-with-sidebar true
gsettings set org.nemo.window-state start-with-status-bar true
gsettings set org.nemo.window-state start-with-toolbar true
