#!/usr/bin/env bash

gsettings reset org.gnome.nautilus.compression default-compression-format
gsettings reset org.gnome.nautilus.icon-view captions
gsettings reset org.gnome.nautilus.icon-view default-zoom-level
gsettings reset org.gnome.nautilus.list-view default-column-order
gsettings reset org.gnome.nautilus.list-view default-visible-columns
gsettings reset org.gnome.nautilus.list-view default-zoom-level
gsettings reset org.gnome.nautilus.list-view use-tree-view
gsettings reset org.gnome.nautilus.preferences always-use-location-entry
gsettings reset org.gnome.nautilus.preferences click-policy
gsettings reset org.gnome.nautilus.preferences date-time-format
gsettings reset org.gnome.nautilus.preferences default-folder-viewer
gsettings reset org.gnome.nautilus.preferences default-sort-in-reverse-order
gsettings reset org.gnome.nautilus.preferences default-sort-order
gsettings reset org.gnome.nautilus.preferences fts-enabled
gsettings reset org.gnome.nautilus.preferences install-mime-activation
gsettings reset org.gnome.nautilus.preferences migrated-gtk-settings
gsettings reset org.gnome.nautilus.preferences mouse-back-button
gsettings reset org.gnome.nautilus.preferences mouse-forward-button
gsettings reset org.gnome.nautilus.preferences mouse-use-extra-buttons
gsettings reset org.gnome.nautilus.preferences open-folder-on-dnd-hover
gsettings reset org.gnome.nautilus.preferences recursive-search
gsettings reset org.gnome.nautilus.preferences search-filter-time-type
gsettings reset org.gnome.nautilus.preferences show-create-link
gsettings reset org.gnome.nautilus.preferences show-delete-permanently
gsettings reset org.gnome.nautilus.preferences show-directory-item-counts
gsettings reset org.gnome.nautilus.preferences show-hidden-files
gsettings reset org.gnome.nautilus.preferences show-image-thumbnails
gsettings reset org.gnome.nautilus.preferences thumbnail-limit
gsettings reset org.gnome.nautilus.window-state initial-size
gsettings reset org.gnome.nautilus.window-state maximized
