#!/usr/bin/env bash

gsettings reset com.gexperts.Tilix.Keybindings app-new-session
gsettings reset com.gexperts.Tilix.Keybindings app-new-window
gsettings reset com.gexperts.Tilix.Keybindings app-preferences
gsettings reset com.gexperts.Tilix.Keybindings app-shortcuts
gsettings reset com.gexperts.Tilix.Keybindings nautilus-open
gsettings reset com.gexperts.Tilix.Keybindings session-add-auto
gsettings reset com.gexperts.Tilix.Keybindings session-add-down
gsettings reset com.gexperts.Tilix.Keybindings session-add-right
gsettings reset com.gexperts.Tilix.Keybindings session-close
gsettings reset com.gexperts.Tilix.Keybindings session-name
gsettings reset com.gexperts.Tilix.Keybindings session-open
gsettings reset com.gexperts.Tilix.Keybindings session-resize-terminal-down
gsettings reset com.gexperts.Tilix.Keybindings session-resize-terminal-left
gsettings reset com.gexperts.Tilix.Keybindings session-resize-terminal-right
gsettings reset com.gexperts.Tilix.Keybindings session-resize-terminal-up
gsettings reset com.gexperts.Tilix.Keybindings session-save
gsettings reset com.gexperts.Tilix.Keybindings session-save-as
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-next-terminal
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-previous-terminal
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-0
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-1
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-2
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-3
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-4
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-5
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-6
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-7
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-8
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-9
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-down
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-left
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-right
gsettings reset com.gexperts.Tilix.Keybindings session-switch-to-terminal-up
gsettings reset com.gexperts.Tilix.Keybindings session-synchronize-input
gsettings reset com.gexperts.Tilix.Keybindings terminal-add-bookmark
gsettings reset com.gexperts.Tilix.Keybindings terminal-advanced-paste
gsettings reset com.gexperts.Tilix.Keybindings terminal-close
gsettings reset com.gexperts.Tilix.Keybindings terminal-copy
gsettings reset com.gexperts.Tilix.Keybindings terminal-copy-as-html
gsettings reset com.gexperts.Tilix.Keybindings terminal-file-browser
gsettings reset com.gexperts.Tilix.Keybindings terminal-find
gsettings reset com.gexperts.Tilix.Keybindings terminal-find-next
gsettings reset com.gexperts.Tilix.Keybindings terminal-find-previous
gsettings reset com.gexperts.Tilix.Keybindings terminal-insert-number
gsettings reset com.gexperts.Tilix.Keybindings terminal-insert-password
gsettings reset com.gexperts.Tilix.Keybindings terminal-layout
gsettings reset com.gexperts.Tilix.Keybindings terminal-maximize
gsettings reset com.gexperts.Tilix.Keybindings terminal-monitor-silence
gsettings reset com.gexperts.Tilix.Keybindings terminal-next-prompt
gsettings reset com.gexperts.Tilix.Keybindings terminal-page-down
gsettings reset com.gexperts.Tilix.Keybindings terminal-page-up
gsettings reset com.gexperts.Tilix.Keybindings terminal-paste
gsettings reset com.gexperts.Tilix.Keybindings terminal-paste-primary
gsettings reset com.gexperts.Tilix.Keybindings terminal-previous-prompt
gsettings reset com.gexperts.Tilix.Keybindings terminal-profile-preference
gsettings reset com.gexperts.Tilix.Keybindings terminal-read-only
gsettings reset com.gexperts.Tilix.Keybindings terminal-reset
gsettings reset com.gexperts.Tilix.Keybindings terminal-reset-and-clear
gsettings reset com.gexperts.Tilix.Keybindings terminal-save
gsettings reset com.gexperts.Tilix.Keybindings terminal-scroll-down
gsettings reset com.gexperts.Tilix.Keybindings terminal-scroll-up
gsettings reset com.gexperts.Tilix.Keybindings terminal-select-all
gsettings reset com.gexperts.Tilix.Keybindings terminal-select-bookmark
gsettings reset com.gexperts.Tilix.Keybindings terminal-sync-input-override
gsettings reset com.gexperts.Tilix.Keybindings terminal-title-style
gsettings reset com.gexperts.Tilix.Keybindings terminal-toggle-margin
gsettings reset com.gexperts.Tilix.Keybindings terminal-unselect-all
gsettings reset com.gexperts.Tilix.Keybindings terminal-zoom-in
gsettings reset com.gexperts.Tilix.Keybindings terminal-zoom-normal
gsettings reset com.gexperts.Tilix.Keybindings terminal-zoom-out
gsettings reset com.gexperts.Tilix.Keybindings win-fullscreen
gsettings reset com.gexperts.Tilix.Keybindings win-reorder-next-session
gsettings reset com.gexperts.Tilix.Keybindings win-reorder-previous-session
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-next-session
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-previous-session
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-0
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-1
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-2
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-3
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-4
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-5
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-6
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-7
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-8
gsettings reset com.gexperts.Tilix.Keybindings win-switch-to-session-9
gsettings reset com.gexperts.Tilix.Keybindings win-view-sidebar
gsettings reset com.gexperts.Tilix.ProfilesList default
gsettings reset com.gexperts.Tilix.ProfilesList list
gsettings reset com.gexperts.Tilix.Settings accelerators-enabled
gsettings reset com.gexperts.Tilix.Settings advanced-paste-replace-crlf
gsettings reset com.gexperts.Tilix.Settings advanced-paste-replace-tabs
gsettings reset com.gexperts.Tilix.Settings advanced-paste-space-count
gsettings reset com.gexperts.Tilix.Settings always-use-regex-in-search
gsettings reset com.gexperts.Tilix.Settings app-title
gsettings reset com.gexperts.Tilix.Settings auto-hide-mouse
gsettings reset com.gexperts.Tilix.Settings background-image
gsettings reset com.gexperts.Tilix.Settings background-image-mode
gsettings reset com.gexperts.Tilix.Settings background-image-scale
gsettings reset com.gexperts.Tilix.Settings bookmark-include-return
gsettings reset com.gexperts.Tilix.Settings close-with-last-session
gsettings reset com.gexperts.Tilix.Settings control-click-titlebar
gsettings reset com.gexperts.Tilix.Settings control-scroll-zoom
gsettings reset com.gexperts.Tilix.Settings copy-on-select
gsettings reset com.gexperts.Tilix.Settings custom-hyperlinks
gsettings reset com.gexperts.Tilix.Settings enable-transparency
gsettings reset com.gexperts.Tilix.Settings enable-wide-handle
gsettings reset com.gexperts.Tilix.Settings encodings
gsettings reset com.gexperts.Tilix.Settings focus-follow-mouse
gsettings reset com.gexperts.Tilix.Settings menu-accelerator-enabled
gsettings reset com.gexperts.Tilix.Settings middle-click-close
gsettings reset com.gexperts.Tilix.Settings new-instance-mode
gsettings reset com.gexperts.Tilix.Settings notify-on-process-complete
gsettings reset com.gexperts.Tilix.Settings password-include-return
gsettings reset com.gexperts.Tilix.Settings paste-advanced-default
gsettings reset com.gexperts.Tilix.Settings paste-strip-first-char
gsettings reset com.gexperts.Tilix.Settings paste-strip-trailing-whitespace
gsettings reset com.gexperts.Tilix.Settings process-monitor
gsettings reset com.gexperts.Tilix.Settings prompt-on-close
gsettings reset com.gexperts.Tilix.Settings prompt-on-close-process
gsettings reset com.gexperts.Tilix.Settings prompt-on-delete-profile
gsettings reset com.gexperts.Tilix.Settings prompt-on-new-session
gsettings reset com.gexperts.Tilix.Settings quake-active-monitor
gsettings reset com.gexperts.Tilix.Settings quake-alignment
gsettings reset com.gexperts.Tilix.Settings quake-height-percent
gsettings reset com.gexperts.Tilix.Settings quake-hide-headerbar
gsettings reset com.gexperts.Tilix.Settings quake-hide-lose-focus
gsettings reset com.gexperts.Tilix.Settings quake-hide-lose-focus-delay
gsettings reset com.gexperts.Tilix.Settings quake-keep-on-top
gsettings reset com.gexperts.Tilix.Settings quake-show-on-all-workspaces
gsettings reset com.gexperts.Tilix.Settings quake-specific-monitor
gsettings reset com.gexperts.Tilix.Settings quake-tab-position
gsettings reset com.gexperts.Tilix.Settings quake-width-percent
gsettings reset com.gexperts.Tilix.Settings quake-window-position
gsettings reset com.gexperts.Tilix.Settings recent-session-files
gsettings reset com.gexperts.Tilix.Settings search-default-match-as-regex
gsettings reset com.gexperts.Tilix.Settings search-default-match-case
gsettings reset com.gexperts.Tilix.Settings search-default-match-entire-word
gsettings reset com.gexperts.Tilix.Settings search-default-wrap-around
gsettings reset com.gexperts.Tilix.Settings session-name
gsettings reset com.gexperts.Tilix.Settings set-proxy-env
gsettings reset com.gexperts.Tilix.Settings sidebar-on-right
gsettings reset com.gexperts.Tilix.Settings tab-position
gsettings reset com.gexperts.Tilix.Settings terminal-title-show-when-single
gsettings reset com.gexperts.Tilix.Settings terminal-title-style
gsettings reset com.gexperts.Tilix.Settings theme-variant
gsettings reset com.gexperts.Tilix.Settings trigger-unlimit-lines
gsettings reset com.gexperts.Tilix.Settings triggers
gsettings reset com.gexperts.Tilix.Settings triggers-lines
gsettings reset com.gexperts.Tilix.Settings unsafe-paste-alert
gsettings reset com.gexperts.Tilix.Settings use-overlay-scrollbar
gsettings reset com.gexperts.Tilix.Settings use-tabs
gsettings reset com.gexperts.Tilix.Settings warn-vte-config-issue
gsettings reset com.gexperts.Tilix.Settings window-save-state
gsettings reset com.gexperts.Tilix.Settings window-state
gsettings reset com.gexperts.Tilix.Settings window-style
