#!/usr/bin/env bash

gsettings set com.gexperts.Tilix.Keybindings app-new-session '<Shift><Ctrl>T'
gsettings set com.gexperts.Tilix.Keybindings app-new-window '<Shift><Ctrl>N'
gsettings set com.gexperts.Tilix.Keybindings app-preferences 'disabled'
gsettings set com.gexperts.Tilix.Keybindings app-shortcuts 'disabled'
gsettings set com.gexperts.Tilix.Keybindings nautilus-open '<Ctrl><Alt>t'
gsettings set com.gexperts.Tilix.Keybindings session-add-auto '<Ctrl><Alt>a'
gsettings set com.gexperts.Tilix.Keybindings session-add-down '<Ctrl><Alt>d'
gsettings set com.gexperts.Tilix.Keybindings session-add-right '<Ctrl><Alt>r'
gsettings set com.gexperts.Tilix.Keybindings session-close '<Shift><Ctrl>Q'
gsettings set com.gexperts.Tilix.Keybindings session-name 'disabled'
gsettings set com.gexperts.Tilix.Keybindings session-open '<Shift><Ctrl>o'
gsettings set com.gexperts.Tilix.Keybindings session-resize-terminal-down '<Shift><Alt>Down'
gsettings set com.gexperts.Tilix.Keybindings session-resize-terminal-left '<Shift><Alt>Left'
gsettings set com.gexperts.Tilix.Keybindings session-resize-terminal-right '<Shift><Alt>Right'
gsettings set com.gexperts.Tilix.Keybindings session-resize-terminal-up '<Shift><Alt>Up'
gsettings set com.gexperts.Tilix.Keybindings session-save '<Shift><Ctrl>s'
gsettings set com.gexperts.Tilix.Keybindings session-save-as 'disabled'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-next-terminal '<Ctrl>Tab'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-previous-terminal '<Ctrl><Shift>Tab'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-0 '<Alt>0'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-1 '<Alt>1'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-2 '<Alt>2'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-3 '<Alt>3'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-4 '<Alt>4'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-5 '<Alt>5'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-6 '<Alt>6'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-7 '<Alt>7'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-8 '<Alt>8'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-9 '<Alt>9'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-down '<Alt>Down'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-left '<Alt>Left'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-right '<Alt>Right'
gsettings set com.gexperts.Tilix.Keybindings session-switch-to-terminal-up '<Alt>Up'
gsettings set com.gexperts.Tilix.Keybindings session-synchronize-input 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-add-bookmark 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-advanced-paste 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-close '<Shift><Ctrl>W'
gsettings set com.gexperts.Tilix.Keybindings terminal-copy '<Ctrl><Shift>c'
gsettings set com.gexperts.Tilix.Keybindings terminal-copy-as-html 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-file-browser 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-find '<Ctrl><Shift>f'
gsettings set com.gexperts.Tilix.Keybindings terminal-find-next '<Ctrl><Shift>g'
gsettings set com.gexperts.Tilix.Keybindings terminal-find-previous '<Ctrl><Shift>h'
gsettings set com.gexperts.Tilix.Keybindings terminal-insert-number 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-insert-password 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-layout 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-maximize '<Shift><Ctrl>X'
gsettings set com.gexperts.Tilix.Keybindings terminal-monitor-silence 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-next-prompt 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-page-down '<Shift>Page_Down'
gsettings set com.gexperts.Tilix.Keybindings terminal-page-up '<Shift>Page_Up'
gsettings set com.gexperts.Tilix.Keybindings terminal-paste '<Ctrl><Shift>v'
gsettings set com.gexperts.Tilix.Keybindings terminal-paste-primary '<Shift>Insert'
gsettings set com.gexperts.Tilix.Keybindings terminal-previous-prompt 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-profile-preference 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-read-only 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-reset 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-reset-and-clear 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-save 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-scroll-down '<Ctrl><Shift>Down'
gsettings set com.gexperts.Tilix.Keybindings terminal-scroll-up '<Ctrl><Shift>Up'
gsettings set com.gexperts.Tilix.Keybindings terminal-select-all '<Ctrl><Shift>a'
gsettings set com.gexperts.Tilix.Keybindings terminal-select-bookmark '<Ctrl><Shift>b'
gsettings set com.gexperts.Tilix.Keybindings terminal-sync-input-override 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-title-style 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-toggle-margin '<Ctrl><Alt>m'
gsettings set com.gexperts.Tilix.Keybindings terminal-unselect-all 'disabled'
gsettings set com.gexperts.Tilix.Keybindings terminal-zoom-in '<Ctrl>plus'
gsettings set com.gexperts.Tilix.Keybindings terminal-zoom-normal '<Ctrl>0'
gsettings set com.gexperts.Tilix.Keybindings terminal-zoom-out '<Ctrl>minus'
gsettings set com.gexperts.Tilix.Keybindings win-fullscreen 'F11'
gsettings set com.gexperts.Tilix.Keybindings win-reorder-next-session '<Ctrl><Shift>Page_Down'
gsettings set com.gexperts.Tilix.Keybindings win-reorder-previous-session '<Ctrl><Shift>Page_Up'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-next-session '<Ctrl>Page_Down'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-previous-session '<Ctrl>Page_Up'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-0 '<Ctrl><Alt>0'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-1 '<Ctrl><Alt>1'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-2 '<Ctrl><Alt>2'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-3 '<Ctrl><Alt>3'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-4 '<Ctrl><Alt>4'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-5 '<Ctrl><Alt>5'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-6 '<Ctrl><Alt>6'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-7 '<Ctrl><Alt>7'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-8 '<Ctrl><Alt>8'
gsettings set com.gexperts.Tilix.Keybindings win-switch-to-session-9 '<Ctrl><Alt>9'
gsettings set com.gexperts.Tilix.Keybindings win-view-sidebar 'F12'
gsettings set com.gexperts.Tilix.ProfilesList default '2b7c4080-0ddd-46c5-8f23-563fd3ba789d'
gsettings set com.gexperts.Tilix.ProfilesList list "['2b7c4080-0ddd-46c5-8f23-563fd3ba789d']"
gsettings set com.gexperts.Tilix.Settings accelerators-enabled true
gsettings set com.gexperts.Tilix.Settings advanced-paste-replace-crlf false
gsettings set com.gexperts.Tilix.Settings advanced-paste-replace-tabs false
gsettings set com.gexperts.Tilix.Settings advanced-paste-space-count 4
gsettings set com.gexperts.Tilix.Settings always-use-regex-in-search false
gsettings set com.gexperts.Tilix.Settings app-title '${appName}: ${sessionName}'
gsettings set com.gexperts.Tilix.Settings auto-hide-mouse false
gsettings set com.gexperts.Tilix.Settings background-image ''
gsettings set com.gexperts.Tilix.Settings background-image-mode 'scale'
gsettings set com.gexperts.Tilix.Settings background-image-scale 'bilinear'
gsettings set com.gexperts.Tilix.Settings bookmark-include-return true
gsettings set com.gexperts.Tilix.Settings close-with-last-session true
gsettings set com.gexperts.Tilix.Settings control-click-titlebar false
gsettings set com.gexperts.Tilix.Settings control-scroll-zoom false
gsettings set com.gexperts.Tilix.Settings copy-on-select true
gsettings set com.gexperts.Tilix.Settings custom-hyperlinks "[]"
gsettings set com.gexperts.Tilix.Settings enable-transparency true
gsettings set com.gexperts.Tilix.Settings enable-wide-handle false
gsettings set com.gexperts.Tilix.Settings encodings "['UTF-8']"
gsettings set com.gexperts.Tilix.Settings focus-follow-mouse false
gsettings set com.gexperts.Tilix.Settings menu-accelerator-enabled false
gsettings set com.gexperts.Tilix.Settings middle-click-close false
gsettings set com.gexperts.Tilix.Settings new-instance-mode 'new-window'
gsettings set com.gexperts.Tilix.Settings notify-on-process-complete true
gsettings set com.gexperts.Tilix.Settings password-include-return true
gsettings set com.gexperts.Tilix.Settings paste-advanced-default false
gsettings set com.gexperts.Tilix.Settings paste-strip-first-char false
gsettings set com.gexperts.Tilix.Settings paste-strip-trailing-whitespace false
gsettings set com.gexperts.Tilix.Settings process-monitor false
gsettings set com.gexperts.Tilix.Settings prompt-on-close true
gsettings set com.gexperts.Tilix.Settings prompt-on-close-process true
gsettings set com.gexperts.Tilix.Settings prompt-on-delete-profile true
gsettings set com.gexperts.Tilix.Settings prompt-on-new-session false
gsettings set com.gexperts.Tilix.Settings quake-active-monitor true
gsettings set com.gexperts.Tilix.Settings quake-alignment 'center'
gsettings set com.gexperts.Tilix.Settings quake-height-percent 40
gsettings set com.gexperts.Tilix.Settings quake-hide-headerbar false
gsettings set com.gexperts.Tilix.Settings quake-hide-lose-focus false
gsettings set com.gexperts.Tilix.Settings quake-hide-lose-focus-delay 150
gsettings set com.gexperts.Tilix.Settings quake-keep-on-top true
gsettings set com.gexperts.Tilix.Settings quake-show-on-all-workspaces true
gsettings set com.gexperts.Tilix.Settings quake-specific-monitor 0
gsettings set com.gexperts.Tilix.Settings quake-tab-position 'top'
gsettings set com.gexperts.Tilix.Settings quake-width-percent 100
gsettings set com.gexperts.Tilix.Settings quake-window-position 'top'
gsettings set com.gexperts.Tilix.Settings recent-session-files "[]"
gsettings set com.gexperts.Tilix.Settings search-default-match-as-regex false
gsettings set com.gexperts.Tilix.Settings search-default-match-case false
gsettings set com.gexperts.Tilix.Settings search-default-match-entire-word false
gsettings set com.gexperts.Tilix.Settings search-default-wrap-around true
gsettings set com.gexperts.Tilix.Settings session-name '${title}'
gsettings set com.gexperts.Tilix.Settings set-proxy-env true
gsettings set com.gexperts.Tilix.Settings sidebar-on-right false
gsettings set com.gexperts.Tilix.Settings tab-position 'top'
gsettings set com.gexperts.Tilix.Settings terminal-title-show-when-single true
gsettings set com.gexperts.Tilix.Settings terminal-title-style 'normal'
gsettings set com.gexperts.Tilix.Settings theme-variant 'dark'
gsettings set com.gexperts.Tilix.Settings trigger-unlimit-lines false
gsettings set com.gexperts.Tilix.Settings triggers "[]"
gsettings set com.gexperts.Tilix.Settings triggers-lines 256
gsettings set com.gexperts.Tilix.Settings unsafe-paste-alert true
gsettings set com.gexperts.Tilix.Settings use-overlay-scrollbar true
gsettings set com.gexperts.Tilix.Settings use-tabs false
gsettings set com.gexperts.Tilix.Settings warn-vte-config-issue false
gsettings set com.gexperts.Tilix.Settings window-save-state false
gsettings set com.gexperts.Tilix.Settings window-state 0
gsettings set com.gexperts.Tilix.Settings window-style 'normal'
